### ISSUE TITLE
Got error with BuildCoinfig.class after updating to 2.0.0

### ISSUE THREAD

**Issue by rassl11** [customerio/customerio-flutter#189]
ERROR:/Users/.gradle/caches/transforms-3/bb8cae490f23f768812abb34c4b78de0/transformed/jetified-android-1.16.3-runtime.jar: R8: Type com.segment.analytics.BuildConfig is defined multiple times: /Users/rasul/.gradle/caches/transforms-3/bb8cae490f23f768812abb34c4b78de0/transformed/jetified-android-1.16.3-runtime.jar:com/segment/analytics/BuildConfig.class, /Users/build/segment_analytics/intermediates/runtime_library_classes_jar/debug/classes.jar:com/segment/analytics/BuildConfig.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyProdDebugWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /Users/.gradle/caches/transforms-3/bb8cae490f23f768812abb34c4b78de0/transformed/jetified-android-1.16.3-runtime.jar:com/segment/analytics/BuildConfig.class

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Error: Gradle task assembleProdDebug failed with exit code 1

**Comment by rassl11** [comment]
environment:
  sdk: ">=3.2.0"

segment_analytics: ^1.1.2
customer_io: ^2.0.0

**Comment by Shahroz16** [comment]
Hey @rassl11, thank you for reaching out, and apologies for the inconvenience. It seems like there is an incompatibility issue with the Segment flutter plugin, we are looking into it.

**Comment by Shahroz16** [comment]
Hey @rassl11, did you manage to solve this? After updating the Flutter version and installing it clean, I am not able to reproduce this issue.

**Comment by rassl11** [comment]
Hi @Shahroz16 still got this error 

ERROR:/Users/.gradle/caches/transforms-3/79e4d0b3a89a48f58a0186d544819392/transformed/jetified-android-1.16.3-runtime.jar: R8: Type com.segment.analytics.BuildConfig is defined multiple times: /Users/.gradle/caches/transforms-3/79e4d0b3a89a48f58a0186d544819392/transformed/jetified-android-1.16.3-runtime.jar:com/segment/analytics/BuildConfig.class, /Users/build/segment_analytics/intermediates/runtime_library_classes_jar/debug/classes.jar:com/segment/analytics/BuildConfig.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyProdDebugWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /Users/.gradle/caches/transforms-3/79e4d0b3a89a48f58a0186d544819392/transformed/jetified-android-1.16.3-runtime.jar:com/segment/analytics/BuildConfig.class


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1 24B83 darwin-arm64, locale ru-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.74.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

environment:
  sdk: ">=3.2.0"

**Comment by Shahroz16** [comment]
Hey @rassl11 I tried reproducing it locally by adding the `segment_analytics` package too but I am unable to reproduce it. 
Can you please share a sample project with CustomerIO installed which can help us reproduce this issue?

**Comment by Shahroz16** [comment]
Closing due to inactivity, feel free to re-open or create a new one if there is new information.

**Comment by Anderzzon** [comment]
I finally got it to work!
I simply removed the line `android.defaults.buildfeatures.buildconfig=true`
in gradle.properties
